language: node_js
node_js:
  - lts/*
cache:
  directories:
    - ~/.npm
before_install: cd twitter-clone-client/
install:
  - npm install
before_script:
  - npm install -g npm@latest
script:
  - npm ci
  - npx jest --ci
