language: node_js
node_js:
  - 10
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
  - cd twitter-clone-client/
install:
  - yarn install
script:
  - yarn test
